import streamlit as st
from langchain_huggingface import HuggingFaceEndpoint
from langchain import PromptTemplate, LLMChain


st.title("Financial Report Generator App")

# openai_api_key = st.sidebar.text_input("OpenAI API Key", type="password")



def load_model(temp,token,repo_id,HF_key,top_p,top_k):
    
    # repo_id="meta-llama/Meta-Llama-3.1-8B-Instruct"
    llm=HuggingFaceEndpoint(repo_id=repo_id,max_new_tokens=token,temperature=temp, huggingfacehub_api_token=HF_key,top_k=top_k,top_p=top_p)
    return llm



system_promt = """

<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are financial adviser.

Using this calculation of financial data as example.

START OF BEV CALCULATION--

Valuation Methodologies Application:

Method Asset-Based Valuation: Explanation: Calculates the net asset value by subtracting total liabilities from total assets. Example: Total Assets = $5,000, Total Liabilities = $3,000, Asset-Based Valuation = $2,000.

Discounted Cash Flow (DCF): Explanation: Projects future cash flows and discounts them back to present value using a discount rate reflecting the risk-adjusted cost of capital. Example: Estimated Future Cash Flows for 5 years sum to $84,000 (assuming growth and discount rate), Discount Rate = 10%, DCF Valuation = $52,155.

Comparable Company Analysis (CCA): Explanation: Evaluates financial ratios and statistics from similar companies to derive a valuation multiple, consider lowest 25 % of population for multiplier. Example: Average PE Ratio of Comparable Firms = 20, Net Profit = $24,000, CCA Valuation = $480,000.

Rule of Thumb Methods: Explanation: Uses industry-specific formulas or averages to estimate business value. Consider lowest 25 % of population for multiplier.Example: Industry Multiplier = 3x Gross Revenue, Gross Revenue = $36,000, Valuation = $108,000.

Earnings Multiplier: Explanation: Multiplies the company\\\\\\\\\\\\\\\\\\\\\'s earnings by a factor typical for the industry or market, consider the average multiplier. Example: Earnings Multiplier = 10, Net Profit = $24,000, Valuation = $240,000.

Liquidation Value: Explanation: Estimates the amount that could be realized if all assets were sold and liabilities paid off today. Example: Total Asset Liquidation Value = $5,000, Liabilities = $3,000, Liquidation Value = $2,000.

Monte Carlo Simulations:
Use probabilistic models to simulate a range of possible outcomes based on the variability of input factors like cash flows, discount rates, and growth projections to provide a valuation range rather than a fixed figure. Calculate the Low , Mid and High Range of monte carlo simulations. Comments what Low, Mid and High ranges could means to the given business.

Geopolitical Events: Consider how local or international political changes could impact the business environment and market stability. Economic Indicators: Include macroeconomic factors such as inflation rates, interest rates, and economic growth rates that could affect the business’s performance. Industry-Specific Trends: Look at growth rates, technological changes, and new regulations affecting the industry. Regulatory Environment: Updates on new laws or regulations that could impact business operations or costs (e.g., environmental regulations, minimum wage increases). Market Competition: Analyze market share, the number of competitors, and their relative size and performance to adjust the valuation accordingly. 

END OF BEV CALCULATION--

--START OF SUMMARY--

From the given financial inputs and using different valuation methods, your Business Estimation Value i.e. BEV is as follows:

1. Asset-Based Valuation:  Provide a simple calculation and explain in one line what it means to the given business.
2. Discounted Cash Flow (DCF): Provide a simple calculation and explain in one line what it means to the given business.
3. Comparable Company Analysis (CCA): Provide a simple calculation and explain in one line what it means to the given business.
4. Rule of Thumb Methods:  This uses industry-specific revenue multipliers to estimate value.Provide a simple calculation and explain in one line what it means to the given business.
5. Earnings Multiplier:  Provide a simple calculation and explain in one line what it means to the given business.
6. Liquidation Value: Provide a simple calculation and explain in one line what it means to the given business.
7. Monte Carlo Simulation Results:
List the Mid and High Range of monte carlo simulations. Provide a simple explanation in one line what it means to the given business.
Valuation Summary : Display Valuation generated by Rule of thumb method and Earnings multiplier

--END OF SUMMARY--

<|eot_id|><|start_header_id|>user<|end_header_id|>

Display all the points i.e. point # 1 to point # 7  of SUMMARY  of gievn data {user_financial_data}. 

Do not display any other section.

Make sure your summary should be based on above calculation only.

<|eot_id|><|start_header_id|>assistant<|end_header_id|>

"""
M_1 ='meta-llama/Meta-Llama-3.1-8B-Instruct'
M_2 ='meta-llama/Meta-Llama-3.1-70B-Instruct'
M_3 ='meta-llama/Meta-Llama-3-8B-Instruct'
M_4 ='mistralai/Mistral-7B-Instruct-v0.2'
M_5= 'google/gemma-2-9b-it'
model_list = [M_1,M_2,M_3,M_4,M_5]

def blog_outline(user_financial_data,temp,token,model,hf_key,t_k,t_p):
    # Instantiate LLM model
    llm = load_model(temp,token,model,HF_key=hf_key,top_k=t_k,top_p=t_p)
    promt= PromptTemplate.from_template(system_promt)
    llm_chain=LLMChain(llm=llm,prompt=promt)
    data = llm_chain.invoke({"user_financial_data":user_financial_data})
    response = data['text']
    return st.info(response)


with st.form("myform"):
    try:
        hf_key = st.sidebar.text_input("HF Key:", "",type="password")

        topic_text = st.text_input("Enter prompt:", "")
        submitted = st.form_submit_button("Submit")
        tokens = st.sidebar.slider(label="Tokens",min_value=500,max_value=2500,value=1200)
        value = st.sidebar.slider(label="Temperature",min_value=0.0,max_value=1.0,value=0.2)
        t_k_value = st.sidebar.slider(label="top_k",min_value=1,max_value=15,value=10)
        t_p_value = st.sidebar.slider(label="top_p",min_value=0.0,max_value=1.0,value=0.75)
        models = st.sidebar.selectbox(label="Select Model",options=model_list)
        if submitted:
           
            blog_outline(user_financial_data=topic_text,
                         temp=value,
                         token=tokens,
                         model=models,
                         hf_key=hf_key,
                         t_k=t_k_value,
                         t_p=t_p_value
                         )

    except Exception as e:
        raise e    
        