from langchain_huggingface import HuggingFaceEndpoint
from langchain import LLMChain
from langchain_core.messages import SystemMessage
from langchain_core.prompts import HumanMessagePromptTemplate 
from langchain_core.prompts import ChatPromptTemplate,PromptTemplate
import streamlit as st


st.title("Financial Report Generator App")

# openai_api_key = st.sidebar.text_input("OpenAI API Key", type="password")



def load_model(temp,token,repo_id,HF_key):
    
    # repo_id="meta-llama/Meta-Llama-3.1-8B-Instruct"
    llm=HuggingFaceEndpoint(repo_id=repo_id,max_new_tokens=token,temperature=temp, huggingfacehub_api_token=HF_key)
    return llm




system_promt12 = """

You are financial adviser.

Using this calculation of financial data as example.

< START OF BEV CALCULATION >

Valuation Methodologies Application:

Method Asset-Based Valuation: Explanation: Calculates the net asset value by subtracting total liabilities from total assets. Example: Total Assets = $5,000, Total Liabilities = $3,000, Asset-Based Valuation = $2,000.

Discounted Cash Flow (DCF): Explanation: Projects future cash flows and discounts them back to present value using a discount rate reflecting the risk-adjusted cost of capital. Example: Estimated Future Cash Flows for 5 years sum to $84,000 (assuming growth and discount rate), Discount Rate = 10%, DCF Valuation = $52,155.

Comparable Company Analysis (CCA): Explanation: Evaluates financial ratios and statistics from similar companies to derive a valuation multiple, consider lowest 25 % of population for multiplier. Example: Average PE Ratio of Comparable Firms = 20, Net Profit = $24,000, CCA Valuation = $480,000.

Rule of Thumb Methods: Explanation: Uses industry-specific formulas or averages to estimate business value. Consider lowest 25 % of population for multiplier.Example: Industry Multiplier = 3x Gross Revenue, Gross Revenue = $36,000, Valuation = $108,000.

Earnings Multiplier: Explanation: Multiplies the company\\\\\\\\\\\\\\\\\\\\\'s earnings by a factor typical for the industry or market, consider the average multiplier. Example: Earnings Multiplier = 10, Net Profit = $24,000, Valuation = $240,000.

Liquidation Value: Explanation: Estimates the amount that could be realized if all assets were sold and liabilities paid off today. Example: Total Asset Liquidation Value = $5,000, Liabilities = $3,000, Liquidation Value = $2,000.

Monte Carlo Simulations:
Use probabilistic models to simulate a range of possible outcomes based on the variability of input factors like cash flows, discount rates, and growth projections to provide a valuation range rather than a fixed figure. Calculate the Low , Mid and High Range of monte carlo simulations. Comments what Low, Mid and High ranges could means to the given business.
External Data Adjustments: 
Check the third-party websites which provides Buy/sell of business.
Geopolitical Events: Consider how local or international political changes could impact the business environment and market stability. Economic Indicators: Include macroeconomic factors such as inflation rates, interest rates, and economic growth rates that could affect the business’s performance. Industry-Specific Trends: Look at growth rates, technological changes, and new regulations affecting the industry. Regulatory Environment: Updates on new laws or regulations that could impact business operations or costs (e.g., environmental regulations, minimum wage increases). Market Competition: Analyze market share, the number of competitors, and their relative size and performance to adjust the valuation accordingly. 

< END OF BEV CALCULATION >

< START OF SUMMARY >

Display all the points i.e. point # 1 to point # 7  of SUMMARY section ( Do not display any other section). 

From the given financial inputs and using different valuation methods, your Business Estimation Value i.e. BEV is as follows:

1. Asset-Based Valuation:  Provide a simple calculation and explain in one line what it means to the given business.
2. Discounted Cash Flow (DCF): Provide a simple calculation and explain in one line what it means to the given business.
3. Comparable Company Analysis (CCA): Provide a simple calculation and explain in one line what it means to the given business.
4. Rule of Thumb Methods:  This uses industry-specific revenue multipliers to estimate value.Provide a simple calculation and explain in one line what it means to the given business.
5. Earnings Multiplier:  Provide a simple calculation and explain in one line what it means to the given business.
6. Liquidation Value: Provide a simple calculation and explain in one line what it means to the given business.
7. Monte Carlo Simulation Results:
List the Mid and High Range of monte carlo simulations. Provide a simple explanation in one line what it means to the given business.
Valuation Summary : Display Valuation generated by Rule of thumb method and Earnings multiplier

< END OF SUMMARY >


"""


M_1 ='meta-llama/Meta-Llama-3.1-8B-Instruct'
M_2 ='google/gemma-2-9b'
M_3 ='meta-llama/Meta-Llama-3-8B-Instruct'
M_4 ='mistralai/Mistral-7B-Instruct-v0.2'
M_5= 'mistralai/Mistral-Nemo-Instruct-2407'

model_list = [M_1,M_2,M_3,M_4,M_5]


def promt_complition(user_question,system_promt1):
    chat_template = ChatPromptTemplate.from_messages(
    [
        SystemMessage(
            content=(
                system_promt1
            )
        ),
        HumanMessagePromptTemplate.from_template("{text}"),
    ]
                                                    )
    messages = chat_template.format_messages(text=user_question)

    return messages


def blog_outline(temp,token,model,query,key,system_promt):
    # Instantiate LLM model
    llm = load_model(temp,token,model,HF_key=key)
    promt= promt_complition(query,system_promt)
    data = llm.invoke(promt).split("}")[1]
    response = data
    return st.info(response)



with st.form("App",border=True):
    try:

        user_query = st.text_input("Enter User Data:", "")
        submitted = st.form_submit_button("Submit")
        keys = st.sidebar.text_input("Enter HF Key",type="password")
        tokens = st.sidebar.slider(label="Tokens",min_value=500,max_value=1500,value=800)
        value = st.sidebar.slider(label="Temperature",min_value=0.1,max_value=1.0,value=0.2)
        models = st.sidebar.selectbox(label="Select Model",options=model_list)
        SysPromt = st.sidebar.text_area("System Prompt:","",height=400)
        if submitted:
            blog_outline(temp=value,token=tokens,model=models,query=user_query,system_promt=SysPromt,key=keys)

    except Exception as e:
        raise e    
        
